# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_fsk4', [dirname(__file__)])
        except ImportError:
            import _fsk4
            return _fsk4
        if fp is not None:
            try:
                _mod = imp.load_module('_fsk4', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _fsk4 = swig_import_helper()
    del swig_import_helper
else:
    import _fsk4
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class fsk4_demod_ff_sptr(object):
    """Proxy of C++ boost::shared_ptr<(fsk4_demod_ff)> class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        __init__(boost::shared_ptr<(fsk4_demod_ff)> self) -> fsk4_demod_ff_sptr
        __init__(boost::shared_ptr<(fsk4_demod_ff)> self, fsk4_demod_ff * p) -> fsk4_demod_ff_sptr
        """
        this = _fsk4.new_fsk4_demod_ff_sptr(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def __deref__(self):
        """__deref__(fsk4_demod_ff_sptr self) -> fsk4_demod_ff *"""
        return _fsk4.fsk4_demod_ff_sptr___deref__(self)

    __swig_destroy__ = _fsk4.delete_fsk4_demod_ff_sptr
    __del__ = lambda self: None

    def history(self):
        """history(fsk4_demod_ff_sptr self) -> unsigned int"""
        return _fsk4.fsk4_demod_ff_sptr_history(self)


    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(fsk4_demod_ff_sptr self, int which, int delay)
        declare_sample_delay(fsk4_demod_ff_sptr self, unsigned int delay)
        """
        return _fsk4.fsk4_demod_ff_sptr_declare_sample_delay(self, *args)


    def sample_delay(self, which):
        """sample_delay(fsk4_demod_ff_sptr self, int which) -> unsigned int"""
        return _fsk4.fsk4_demod_ff_sptr_sample_delay(self, which)


    def output_multiple(self):
        """output_multiple(fsk4_demod_ff_sptr self) -> int"""
        return _fsk4.fsk4_demod_ff_sptr_output_multiple(self)


    def relative_rate(self):
        """relative_rate(fsk4_demod_ff_sptr self) -> double"""
        return _fsk4.fsk4_demod_ff_sptr_relative_rate(self)


    def start(self):
        """start(fsk4_demod_ff_sptr self) -> bool"""
        return _fsk4.fsk4_demod_ff_sptr_start(self)


    def stop(self):
        """stop(fsk4_demod_ff_sptr self) -> bool"""
        return _fsk4.fsk4_demod_ff_sptr_stop(self)


    def nitems_read(self, which_input):
        """nitems_read(fsk4_demod_ff_sptr self, unsigned int which_input) -> uint64_t"""
        return _fsk4.fsk4_demod_ff_sptr_nitems_read(self, which_input)


    def nitems_written(self, which_output):
        """nitems_written(fsk4_demod_ff_sptr self, unsigned int which_output) -> uint64_t"""
        return _fsk4.fsk4_demod_ff_sptr_nitems_written(self, which_output)


    def max_noutput_items(self):
        """max_noutput_items(fsk4_demod_ff_sptr self) -> int"""
        return _fsk4.fsk4_demod_ff_sptr_max_noutput_items(self)


    def set_max_noutput_items(self, m):
        """set_max_noutput_items(fsk4_demod_ff_sptr self, int m)"""
        return _fsk4.fsk4_demod_ff_sptr_set_max_noutput_items(self, m)


    def unset_max_noutput_items(self):
        """unset_max_noutput_items(fsk4_demod_ff_sptr self)"""
        return _fsk4.fsk4_demod_ff_sptr_unset_max_noutput_items(self)


    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(fsk4_demod_ff_sptr self) -> bool"""
        return _fsk4.fsk4_demod_ff_sptr_is_set_max_noutput_items(self)


    def set_min_noutput_items(self, m):
        """set_min_noutput_items(fsk4_demod_ff_sptr self, int m)"""
        return _fsk4.fsk4_demod_ff_sptr_set_min_noutput_items(self, m)


    def min_noutput_items(self):
        """min_noutput_items(fsk4_demod_ff_sptr self) -> int"""
        return _fsk4.fsk4_demod_ff_sptr_min_noutput_items(self)


    def max_output_buffer(self, i):
        """max_output_buffer(fsk4_demod_ff_sptr self, int i) -> long"""
        return _fsk4.fsk4_demod_ff_sptr_max_output_buffer(self, i)


    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(fsk4_demod_ff_sptr self, long max_output_buffer)
        set_max_output_buffer(fsk4_demod_ff_sptr self, int port, long max_output_buffer)
        """
        return _fsk4.fsk4_demod_ff_sptr_set_max_output_buffer(self, *args)


    def min_output_buffer(self, i):
        """min_output_buffer(fsk4_demod_ff_sptr self, int i) -> long"""
        return _fsk4.fsk4_demod_ff_sptr_min_output_buffer(self, i)


    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(fsk4_demod_ff_sptr self, long min_output_buffer)
        set_min_output_buffer(fsk4_demod_ff_sptr self, int port, long min_output_buffer)
        """
        return _fsk4.fsk4_demod_ff_sptr_set_min_output_buffer(self, *args)


    def pc_noutput_items(self):
        """pc_noutput_items(fsk4_demod_ff_sptr self) -> float"""
        return _fsk4.fsk4_demod_ff_sptr_pc_noutput_items(self)


    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(fsk4_demod_ff_sptr self) -> float"""
        return _fsk4.fsk4_demod_ff_sptr_pc_noutput_items_avg(self)


    def pc_noutput_items_var(self):
        """pc_noutput_items_var(fsk4_demod_ff_sptr self) -> float"""
        return _fsk4.fsk4_demod_ff_sptr_pc_noutput_items_var(self)


    def pc_nproduced(self):
        """pc_nproduced(fsk4_demod_ff_sptr self) -> float"""
        return _fsk4.fsk4_demod_ff_sptr_pc_nproduced(self)


    def pc_nproduced_avg(self):
        """pc_nproduced_avg(fsk4_demod_ff_sptr self) -> float"""
        return _fsk4.fsk4_demod_ff_sptr_pc_nproduced_avg(self)


    def pc_nproduced_var(self):
        """pc_nproduced_var(fsk4_demod_ff_sptr self) -> float"""
        return _fsk4.fsk4_demod_ff_sptr_pc_nproduced_var(self)


    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(fsk4_demod_ff_sptr self, int which) -> float
        pc_input_buffers_full(fsk4_demod_ff_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_demod_ff_sptr_pc_input_buffers_full(self, *args)


    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(fsk4_demod_ff_sptr self, int which) -> float
        pc_input_buffers_full_avg(fsk4_demod_ff_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_demod_ff_sptr_pc_input_buffers_full_avg(self, *args)


    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(fsk4_demod_ff_sptr self, int which) -> float
        pc_input_buffers_full_var(fsk4_demod_ff_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_demod_ff_sptr_pc_input_buffers_full_var(self, *args)


    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(fsk4_demod_ff_sptr self, int which) -> float
        pc_output_buffers_full(fsk4_demod_ff_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_demod_ff_sptr_pc_output_buffers_full(self, *args)


    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(fsk4_demod_ff_sptr self, int which) -> float
        pc_output_buffers_full_avg(fsk4_demod_ff_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_demod_ff_sptr_pc_output_buffers_full_avg(self, *args)


    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(fsk4_demod_ff_sptr self, int which) -> float
        pc_output_buffers_full_var(fsk4_demod_ff_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_demod_ff_sptr_pc_output_buffers_full_var(self, *args)


    def pc_work_time(self):
        """pc_work_time(fsk4_demod_ff_sptr self) -> float"""
        return _fsk4.fsk4_demod_ff_sptr_pc_work_time(self)


    def pc_work_time_avg(self):
        """pc_work_time_avg(fsk4_demod_ff_sptr self) -> float"""
        return _fsk4.fsk4_demod_ff_sptr_pc_work_time_avg(self)


    def pc_work_time_var(self):
        """pc_work_time_var(fsk4_demod_ff_sptr self) -> float"""
        return _fsk4.fsk4_demod_ff_sptr_pc_work_time_var(self)


    def pc_work_time_total(self):
        """pc_work_time_total(fsk4_demod_ff_sptr self) -> float"""
        return _fsk4.fsk4_demod_ff_sptr_pc_work_time_total(self)


    def pc_throughput_avg(self):
        """pc_throughput_avg(fsk4_demod_ff_sptr self) -> float"""
        return _fsk4.fsk4_demod_ff_sptr_pc_throughput_avg(self)


    def set_processor_affinity(self, mask):
        """set_processor_affinity(fsk4_demod_ff_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _fsk4.fsk4_demod_ff_sptr_set_processor_affinity(self, mask)


    def unset_processor_affinity(self):
        """unset_processor_affinity(fsk4_demod_ff_sptr self)"""
        return _fsk4.fsk4_demod_ff_sptr_unset_processor_affinity(self)


    def processor_affinity(self):
        """processor_affinity(fsk4_demod_ff_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _fsk4.fsk4_demod_ff_sptr_processor_affinity(self)


    def active_thread_priority(self):
        """active_thread_priority(fsk4_demod_ff_sptr self) -> int"""
        return _fsk4.fsk4_demod_ff_sptr_active_thread_priority(self)


    def thread_priority(self):
        """thread_priority(fsk4_demod_ff_sptr self) -> int"""
        return _fsk4.fsk4_demod_ff_sptr_thread_priority(self)


    def set_thread_priority(self, priority):
        """set_thread_priority(fsk4_demod_ff_sptr self, int priority) -> int"""
        return _fsk4.fsk4_demod_ff_sptr_set_thread_priority(self, priority)


    def name(self):
        """name(fsk4_demod_ff_sptr self) -> std::string"""
        return _fsk4.fsk4_demod_ff_sptr_name(self)


    def symbol_name(self):
        """symbol_name(fsk4_demod_ff_sptr self) -> std::string"""
        return _fsk4.fsk4_demod_ff_sptr_symbol_name(self)


    def input_signature(self):
        """input_signature(fsk4_demod_ff_sptr self) -> io_signature_sptr"""
        return _fsk4.fsk4_demod_ff_sptr_input_signature(self)


    def output_signature(self):
        """output_signature(fsk4_demod_ff_sptr self) -> io_signature_sptr"""
        return _fsk4.fsk4_demod_ff_sptr_output_signature(self)


    def unique_id(self):
        """unique_id(fsk4_demod_ff_sptr self) -> long"""
        return _fsk4.fsk4_demod_ff_sptr_unique_id(self)


    def to_basic_block(self):
        """to_basic_block(fsk4_demod_ff_sptr self) -> basic_block_sptr"""
        return _fsk4.fsk4_demod_ff_sptr_to_basic_block(self)


    def check_topology(self, ninputs, noutputs):
        """check_topology(fsk4_demod_ff_sptr self, int ninputs, int noutputs) -> bool"""
        return _fsk4.fsk4_demod_ff_sptr_check_topology(self, ninputs, noutputs)


    def alias(self):
        """alias(fsk4_demod_ff_sptr self) -> std::string"""
        return _fsk4.fsk4_demod_ff_sptr_alias(self)


    def set_block_alias(self, name):
        """set_block_alias(fsk4_demod_ff_sptr self, std::string name)"""
        return _fsk4.fsk4_demod_ff_sptr_set_block_alias(self, name)


    def _post(self, which_port, msg):
        """_post(fsk4_demod_ff_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _fsk4.fsk4_demod_ff_sptr__post(self, which_port, msg)


    def message_ports_in(self):
        """message_ports_in(fsk4_demod_ff_sptr self) -> swig_int_ptr"""
        return _fsk4.fsk4_demod_ff_sptr_message_ports_in(self)


    def message_ports_out(self):
        """message_ports_out(fsk4_demod_ff_sptr self) -> swig_int_ptr"""
        return _fsk4.fsk4_demod_ff_sptr_message_ports_out(self)


    def message_subscribers(self, which_port):
        """message_subscribers(fsk4_demod_ff_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _fsk4.fsk4_demod_ff_sptr_message_subscribers(self, which_port)

fsk4_demod_ff_sptr_swigregister = _fsk4.fsk4_demod_ff_sptr_swigregister
fsk4_demod_ff_sptr_swigregister(fsk4_demod_ff_sptr)


fsk4_demod_ff_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id ())


def demod_ff(queue, sample_rate, symbol_rate):
    """demod_ff(msg_queue_sptr queue, float sample_rate, float symbol_rate) -> fsk4_demod_ff_sptr"""
    return _fsk4.demod_ff(queue, sample_rate, symbol_rate)
class fsk4_rdlap_f_sptr(object):
    """Proxy of C++ boost::shared_ptr<(fsk4_rdlap_f)> class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        __init__(boost::shared_ptr<(fsk4_rdlap_f)> self) -> fsk4_rdlap_f_sptr
        __init__(boost::shared_ptr<(fsk4_rdlap_f)> self, fsk4_rdlap_f * p) -> fsk4_rdlap_f_sptr
        """
        this = _fsk4.new_fsk4_rdlap_f_sptr(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def __deref__(self):
        """__deref__(fsk4_rdlap_f_sptr self) -> fsk4_rdlap_f *"""
        return _fsk4.fsk4_rdlap_f_sptr___deref__(self)

    __swig_destroy__ = _fsk4.delete_fsk4_rdlap_f_sptr
    __del__ = lambda self: None

    def history(self):
        """history(fsk4_rdlap_f_sptr self) -> unsigned int"""
        return _fsk4.fsk4_rdlap_f_sptr_history(self)


    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(fsk4_rdlap_f_sptr self, int which, int delay)
        declare_sample_delay(fsk4_rdlap_f_sptr self, unsigned int delay)
        """
        return _fsk4.fsk4_rdlap_f_sptr_declare_sample_delay(self, *args)


    def sample_delay(self, which):
        """sample_delay(fsk4_rdlap_f_sptr self, int which) -> unsigned int"""
        return _fsk4.fsk4_rdlap_f_sptr_sample_delay(self, which)


    def output_multiple(self):
        """output_multiple(fsk4_rdlap_f_sptr self) -> int"""
        return _fsk4.fsk4_rdlap_f_sptr_output_multiple(self)


    def relative_rate(self):
        """relative_rate(fsk4_rdlap_f_sptr self) -> double"""
        return _fsk4.fsk4_rdlap_f_sptr_relative_rate(self)


    def start(self):
        """start(fsk4_rdlap_f_sptr self) -> bool"""
        return _fsk4.fsk4_rdlap_f_sptr_start(self)


    def stop(self):
        """stop(fsk4_rdlap_f_sptr self) -> bool"""
        return _fsk4.fsk4_rdlap_f_sptr_stop(self)


    def nitems_read(self, which_input):
        """nitems_read(fsk4_rdlap_f_sptr self, unsigned int which_input) -> uint64_t"""
        return _fsk4.fsk4_rdlap_f_sptr_nitems_read(self, which_input)


    def nitems_written(self, which_output):
        """nitems_written(fsk4_rdlap_f_sptr self, unsigned int which_output) -> uint64_t"""
        return _fsk4.fsk4_rdlap_f_sptr_nitems_written(self, which_output)


    def max_noutput_items(self):
        """max_noutput_items(fsk4_rdlap_f_sptr self) -> int"""
        return _fsk4.fsk4_rdlap_f_sptr_max_noutput_items(self)


    def set_max_noutput_items(self, m):
        """set_max_noutput_items(fsk4_rdlap_f_sptr self, int m)"""
        return _fsk4.fsk4_rdlap_f_sptr_set_max_noutput_items(self, m)


    def unset_max_noutput_items(self):
        """unset_max_noutput_items(fsk4_rdlap_f_sptr self)"""
        return _fsk4.fsk4_rdlap_f_sptr_unset_max_noutput_items(self)


    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(fsk4_rdlap_f_sptr self) -> bool"""
        return _fsk4.fsk4_rdlap_f_sptr_is_set_max_noutput_items(self)


    def set_min_noutput_items(self, m):
        """set_min_noutput_items(fsk4_rdlap_f_sptr self, int m)"""
        return _fsk4.fsk4_rdlap_f_sptr_set_min_noutput_items(self, m)


    def min_noutput_items(self):
        """min_noutput_items(fsk4_rdlap_f_sptr self) -> int"""
        return _fsk4.fsk4_rdlap_f_sptr_min_noutput_items(self)


    def max_output_buffer(self, i):
        """max_output_buffer(fsk4_rdlap_f_sptr self, int i) -> long"""
        return _fsk4.fsk4_rdlap_f_sptr_max_output_buffer(self, i)


    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(fsk4_rdlap_f_sptr self, long max_output_buffer)
        set_max_output_buffer(fsk4_rdlap_f_sptr self, int port, long max_output_buffer)
        """
        return _fsk4.fsk4_rdlap_f_sptr_set_max_output_buffer(self, *args)


    def min_output_buffer(self, i):
        """min_output_buffer(fsk4_rdlap_f_sptr self, int i) -> long"""
        return _fsk4.fsk4_rdlap_f_sptr_min_output_buffer(self, i)


    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(fsk4_rdlap_f_sptr self, long min_output_buffer)
        set_min_output_buffer(fsk4_rdlap_f_sptr self, int port, long min_output_buffer)
        """
        return _fsk4.fsk4_rdlap_f_sptr_set_min_output_buffer(self, *args)


    def pc_noutput_items(self):
        """pc_noutput_items(fsk4_rdlap_f_sptr self) -> float"""
        return _fsk4.fsk4_rdlap_f_sptr_pc_noutput_items(self)


    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(fsk4_rdlap_f_sptr self) -> float"""
        return _fsk4.fsk4_rdlap_f_sptr_pc_noutput_items_avg(self)


    def pc_noutput_items_var(self):
        """pc_noutput_items_var(fsk4_rdlap_f_sptr self) -> float"""
        return _fsk4.fsk4_rdlap_f_sptr_pc_noutput_items_var(self)


    def pc_nproduced(self):
        """pc_nproduced(fsk4_rdlap_f_sptr self) -> float"""
        return _fsk4.fsk4_rdlap_f_sptr_pc_nproduced(self)


    def pc_nproduced_avg(self):
        """pc_nproduced_avg(fsk4_rdlap_f_sptr self) -> float"""
        return _fsk4.fsk4_rdlap_f_sptr_pc_nproduced_avg(self)


    def pc_nproduced_var(self):
        """pc_nproduced_var(fsk4_rdlap_f_sptr self) -> float"""
        return _fsk4.fsk4_rdlap_f_sptr_pc_nproduced_var(self)


    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(fsk4_rdlap_f_sptr self, int which) -> float
        pc_input_buffers_full(fsk4_rdlap_f_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_rdlap_f_sptr_pc_input_buffers_full(self, *args)


    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(fsk4_rdlap_f_sptr self, int which) -> float
        pc_input_buffers_full_avg(fsk4_rdlap_f_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_rdlap_f_sptr_pc_input_buffers_full_avg(self, *args)


    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(fsk4_rdlap_f_sptr self, int which) -> float
        pc_input_buffers_full_var(fsk4_rdlap_f_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_rdlap_f_sptr_pc_input_buffers_full_var(self, *args)


    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(fsk4_rdlap_f_sptr self, int which) -> float
        pc_output_buffers_full(fsk4_rdlap_f_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_rdlap_f_sptr_pc_output_buffers_full(self, *args)


    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(fsk4_rdlap_f_sptr self, int which) -> float
        pc_output_buffers_full_avg(fsk4_rdlap_f_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_rdlap_f_sptr_pc_output_buffers_full_avg(self, *args)


    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(fsk4_rdlap_f_sptr self, int which) -> float
        pc_output_buffers_full_var(fsk4_rdlap_f_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_rdlap_f_sptr_pc_output_buffers_full_var(self, *args)


    def pc_work_time(self):
        """pc_work_time(fsk4_rdlap_f_sptr self) -> float"""
        return _fsk4.fsk4_rdlap_f_sptr_pc_work_time(self)


    def pc_work_time_avg(self):
        """pc_work_time_avg(fsk4_rdlap_f_sptr self) -> float"""
        return _fsk4.fsk4_rdlap_f_sptr_pc_work_time_avg(self)


    def pc_work_time_var(self):
        """pc_work_time_var(fsk4_rdlap_f_sptr self) -> float"""
        return _fsk4.fsk4_rdlap_f_sptr_pc_work_time_var(self)


    def pc_work_time_total(self):
        """pc_work_time_total(fsk4_rdlap_f_sptr self) -> float"""
        return _fsk4.fsk4_rdlap_f_sptr_pc_work_time_total(self)


    def pc_throughput_avg(self):
        """pc_throughput_avg(fsk4_rdlap_f_sptr self) -> float"""
        return _fsk4.fsk4_rdlap_f_sptr_pc_throughput_avg(self)


    def set_processor_affinity(self, mask):
        """set_processor_affinity(fsk4_rdlap_f_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _fsk4.fsk4_rdlap_f_sptr_set_processor_affinity(self, mask)


    def unset_processor_affinity(self):
        """unset_processor_affinity(fsk4_rdlap_f_sptr self)"""
        return _fsk4.fsk4_rdlap_f_sptr_unset_processor_affinity(self)


    def processor_affinity(self):
        """processor_affinity(fsk4_rdlap_f_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _fsk4.fsk4_rdlap_f_sptr_processor_affinity(self)


    def active_thread_priority(self):
        """active_thread_priority(fsk4_rdlap_f_sptr self) -> int"""
        return _fsk4.fsk4_rdlap_f_sptr_active_thread_priority(self)


    def thread_priority(self):
        """thread_priority(fsk4_rdlap_f_sptr self) -> int"""
        return _fsk4.fsk4_rdlap_f_sptr_thread_priority(self)


    def set_thread_priority(self, priority):
        """set_thread_priority(fsk4_rdlap_f_sptr self, int priority) -> int"""
        return _fsk4.fsk4_rdlap_f_sptr_set_thread_priority(self, priority)


    def name(self):
        """name(fsk4_rdlap_f_sptr self) -> std::string"""
        return _fsk4.fsk4_rdlap_f_sptr_name(self)


    def symbol_name(self):
        """symbol_name(fsk4_rdlap_f_sptr self) -> std::string"""
        return _fsk4.fsk4_rdlap_f_sptr_symbol_name(self)


    def input_signature(self):
        """input_signature(fsk4_rdlap_f_sptr self) -> io_signature_sptr"""
        return _fsk4.fsk4_rdlap_f_sptr_input_signature(self)


    def output_signature(self):
        """output_signature(fsk4_rdlap_f_sptr self) -> io_signature_sptr"""
        return _fsk4.fsk4_rdlap_f_sptr_output_signature(self)


    def unique_id(self):
        """unique_id(fsk4_rdlap_f_sptr self) -> long"""
        return _fsk4.fsk4_rdlap_f_sptr_unique_id(self)


    def to_basic_block(self):
        """to_basic_block(fsk4_rdlap_f_sptr self) -> basic_block_sptr"""
        return _fsk4.fsk4_rdlap_f_sptr_to_basic_block(self)


    def check_topology(self, ninputs, noutputs):
        """check_topology(fsk4_rdlap_f_sptr self, int ninputs, int noutputs) -> bool"""
        return _fsk4.fsk4_rdlap_f_sptr_check_topology(self, ninputs, noutputs)


    def alias(self):
        """alias(fsk4_rdlap_f_sptr self) -> std::string"""
        return _fsk4.fsk4_rdlap_f_sptr_alias(self)


    def set_block_alias(self, name):
        """set_block_alias(fsk4_rdlap_f_sptr self, std::string name)"""
        return _fsk4.fsk4_rdlap_f_sptr_set_block_alias(self, name)


    def _post(self, which_port, msg):
        """_post(fsk4_rdlap_f_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _fsk4.fsk4_rdlap_f_sptr__post(self, which_port, msg)


    def message_ports_in(self):
        """message_ports_in(fsk4_rdlap_f_sptr self) -> swig_int_ptr"""
        return _fsk4.fsk4_rdlap_f_sptr_message_ports_in(self)


    def message_ports_out(self):
        """message_ports_out(fsk4_rdlap_f_sptr self) -> swig_int_ptr"""
        return _fsk4.fsk4_rdlap_f_sptr_message_ports_out(self)


    def message_subscribers(self, which_port):
        """message_subscribers(fsk4_rdlap_f_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _fsk4.fsk4_rdlap_f_sptr_message_subscribers(self, which_port)

fsk4_rdlap_f_sptr_swigregister = _fsk4.fsk4_rdlap_f_sptr_swigregister
fsk4_rdlap_f_sptr_swigregister(fsk4_rdlap_f_sptr)


fsk4_rdlap_f_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id ())


def rdlap_f(queue, processing_flags):
    """rdlap_f(msg_queue_sptr queue, int processing_flags) -> fsk4_rdlap_f_sptr"""
    return _fsk4.rdlap_f(queue, processing_flags)
class fsk4_generic_f_sptr(object):
    """Proxy of C++ boost::shared_ptr<(fsk4_generic_f)> class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        __init__(boost::shared_ptr<(fsk4_generic_f)> self) -> fsk4_generic_f_sptr
        __init__(boost::shared_ptr<(fsk4_generic_f)> self, fsk4_generic_f * p) -> fsk4_generic_f_sptr
        """
        this = _fsk4.new_fsk4_generic_f_sptr(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def __deref__(self):
        """__deref__(fsk4_generic_f_sptr self) -> fsk4_generic_f *"""
        return _fsk4.fsk4_generic_f_sptr___deref__(self)

    __swig_destroy__ = _fsk4.delete_fsk4_generic_f_sptr
    __del__ = lambda self: None

    def history(self):
        """history(fsk4_generic_f_sptr self) -> unsigned int"""
        return _fsk4.fsk4_generic_f_sptr_history(self)


    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(fsk4_generic_f_sptr self, int which, int delay)
        declare_sample_delay(fsk4_generic_f_sptr self, unsigned int delay)
        """
        return _fsk4.fsk4_generic_f_sptr_declare_sample_delay(self, *args)


    def sample_delay(self, which):
        """sample_delay(fsk4_generic_f_sptr self, int which) -> unsigned int"""
        return _fsk4.fsk4_generic_f_sptr_sample_delay(self, which)


    def output_multiple(self):
        """output_multiple(fsk4_generic_f_sptr self) -> int"""
        return _fsk4.fsk4_generic_f_sptr_output_multiple(self)


    def relative_rate(self):
        """relative_rate(fsk4_generic_f_sptr self) -> double"""
        return _fsk4.fsk4_generic_f_sptr_relative_rate(self)


    def start(self):
        """start(fsk4_generic_f_sptr self) -> bool"""
        return _fsk4.fsk4_generic_f_sptr_start(self)


    def stop(self):
        """stop(fsk4_generic_f_sptr self) -> bool"""
        return _fsk4.fsk4_generic_f_sptr_stop(self)


    def nitems_read(self, which_input):
        """nitems_read(fsk4_generic_f_sptr self, unsigned int which_input) -> uint64_t"""
        return _fsk4.fsk4_generic_f_sptr_nitems_read(self, which_input)


    def nitems_written(self, which_output):
        """nitems_written(fsk4_generic_f_sptr self, unsigned int which_output) -> uint64_t"""
        return _fsk4.fsk4_generic_f_sptr_nitems_written(self, which_output)


    def max_noutput_items(self):
        """max_noutput_items(fsk4_generic_f_sptr self) -> int"""
        return _fsk4.fsk4_generic_f_sptr_max_noutput_items(self)


    def set_max_noutput_items(self, m):
        """set_max_noutput_items(fsk4_generic_f_sptr self, int m)"""
        return _fsk4.fsk4_generic_f_sptr_set_max_noutput_items(self, m)


    def unset_max_noutput_items(self):
        """unset_max_noutput_items(fsk4_generic_f_sptr self)"""
        return _fsk4.fsk4_generic_f_sptr_unset_max_noutput_items(self)


    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(fsk4_generic_f_sptr self) -> bool"""
        return _fsk4.fsk4_generic_f_sptr_is_set_max_noutput_items(self)


    def set_min_noutput_items(self, m):
        """set_min_noutput_items(fsk4_generic_f_sptr self, int m)"""
        return _fsk4.fsk4_generic_f_sptr_set_min_noutput_items(self, m)


    def min_noutput_items(self):
        """min_noutput_items(fsk4_generic_f_sptr self) -> int"""
        return _fsk4.fsk4_generic_f_sptr_min_noutput_items(self)


    def max_output_buffer(self, i):
        """max_output_buffer(fsk4_generic_f_sptr self, int i) -> long"""
        return _fsk4.fsk4_generic_f_sptr_max_output_buffer(self, i)


    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(fsk4_generic_f_sptr self, long max_output_buffer)
        set_max_output_buffer(fsk4_generic_f_sptr self, int port, long max_output_buffer)
        """
        return _fsk4.fsk4_generic_f_sptr_set_max_output_buffer(self, *args)


    def min_output_buffer(self, i):
        """min_output_buffer(fsk4_generic_f_sptr self, int i) -> long"""
        return _fsk4.fsk4_generic_f_sptr_min_output_buffer(self, i)


    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(fsk4_generic_f_sptr self, long min_output_buffer)
        set_min_output_buffer(fsk4_generic_f_sptr self, int port, long min_output_buffer)
        """
        return _fsk4.fsk4_generic_f_sptr_set_min_output_buffer(self, *args)


    def pc_noutput_items(self):
        """pc_noutput_items(fsk4_generic_f_sptr self) -> float"""
        return _fsk4.fsk4_generic_f_sptr_pc_noutput_items(self)


    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(fsk4_generic_f_sptr self) -> float"""
        return _fsk4.fsk4_generic_f_sptr_pc_noutput_items_avg(self)


    def pc_noutput_items_var(self):
        """pc_noutput_items_var(fsk4_generic_f_sptr self) -> float"""
        return _fsk4.fsk4_generic_f_sptr_pc_noutput_items_var(self)


    def pc_nproduced(self):
        """pc_nproduced(fsk4_generic_f_sptr self) -> float"""
        return _fsk4.fsk4_generic_f_sptr_pc_nproduced(self)


    def pc_nproduced_avg(self):
        """pc_nproduced_avg(fsk4_generic_f_sptr self) -> float"""
        return _fsk4.fsk4_generic_f_sptr_pc_nproduced_avg(self)


    def pc_nproduced_var(self):
        """pc_nproduced_var(fsk4_generic_f_sptr self) -> float"""
        return _fsk4.fsk4_generic_f_sptr_pc_nproduced_var(self)


    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(fsk4_generic_f_sptr self, int which) -> float
        pc_input_buffers_full(fsk4_generic_f_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_generic_f_sptr_pc_input_buffers_full(self, *args)


    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(fsk4_generic_f_sptr self, int which) -> float
        pc_input_buffers_full_avg(fsk4_generic_f_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_generic_f_sptr_pc_input_buffers_full_avg(self, *args)


    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(fsk4_generic_f_sptr self, int which) -> float
        pc_input_buffers_full_var(fsk4_generic_f_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_generic_f_sptr_pc_input_buffers_full_var(self, *args)


    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(fsk4_generic_f_sptr self, int which) -> float
        pc_output_buffers_full(fsk4_generic_f_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_generic_f_sptr_pc_output_buffers_full(self, *args)


    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(fsk4_generic_f_sptr self, int which) -> float
        pc_output_buffers_full_avg(fsk4_generic_f_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_generic_f_sptr_pc_output_buffers_full_avg(self, *args)


    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(fsk4_generic_f_sptr self, int which) -> float
        pc_output_buffers_full_var(fsk4_generic_f_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_generic_f_sptr_pc_output_buffers_full_var(self, *args)


    def pc_work_time(self):
        """pc_work_time(fsk4_generic_f_sptr self) -> float"""
        return _fsk4.fsk4_generic_f_sptr_pc_work_time(self)


    def pc_work_time_avg(self):
        """pc_work_time_avg(fsk4_generic_f_sptr self) -> float"""
        return _fsk4.fsk4_generic_f_sptr_pc_work_time_avg(self)


    def pc_work_time_var(self):
        """pc_work_time_var(fsk4_generic_f_sptr self) -> float"""
        return _fsk4.fsk4_generic_f_sptr_pc_work_time_var(self)


    def pc_work_time_total(self):
        """pc_work_time_total(fsk4_generic_f_sptr self) -> float"""
        return _fsk4.fsk4_generic_f_sptr_pc_work_time_total(self)


    def pc_throughput_avg(self):
        """pc_throughput_avg(fsk4_generic_f_sptr self) -> float"""
        return _fsk4.fsk4_generic_f_sptr_pc_throughput_avg(self)


    def set_processor_affinity(self, mask):
        """set_processor_affinity(fsk4_generic_f_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _fsk4.fsk4_generic_f_sptr_set_processor_affinity(self, mask)


    def unset_processor_affinity(self):
        """unset_processor_affinity(fsk4_generic_f_sptr self)"""
        return _fsk4.fsk4_generic_f_sptr_unset_processor_affinity(self)


    def processor_affinity(self):
        """processor_affinity(fsk4_generic_f_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _fsk4.fsk4_generic_f_sptr_processor_affinity(self)


    def active_thread_priority(self):
        """active_thread_priority(fsk4_generic_f_sptr self) -> int"""
        return _fsk4.fsk4_generic_f_sptr_active_thread_priority(self)


    def thread_priority(self):
        """thread_priority(fsk4_generic_f_sptr self) -> int"""
        return _fsk4.fsk4_generic_f_sptr_thread_priority(self)


    def set_thread_priority(self, priority):
        """set_thread_priority(fsk4_generic_f_sptr self, int priority) -> int"""
        return _fsk4.fsk4_generic_f_sptr_set_thread_priority(self, priority)


    def name(self):
        """name(fsk4_generic_f_sptr self) -> std::string"""
        return _fsk4.fsk4_generic_f_sptr_name(self)


    def symbol_name(self):
        """symbol_name(fsk4_generic_f_sptr self) -> std::string"""
        return _fsk4.fsk4_generic_f_sptr_symbol_name(self)


    def input_signature(self):
        """input_signature(fsk4_generic_f_sptr self) -> io_signature_sptr"""
        return _fsk4.fsk4_generic_f_sptr_input_signature(self)


    def output_signature(self):
        """output_signature(fsk4_generic_f_sptr self) -> io_signature_sptr"""
        return _fsk4.fsk4_generic_f_sptr_output_signature(self)


    def unique_id(self):
        """unique_id(fsk4_generic_f_sptr self) -> long"""
        return _fsk4.fsk4_generic_f_sptr_unique_id(self)


    def to_basic_block(self):
        """to_basic_block(fsk4_generic_f_sptr self) -> basic_block_sptr"""
        return _fsk4.fsk4_generic_f_sptr_to_basic_block(self)


    def check_topology(self, ninputs, noutputs):
        """check_topology(fsk4_generic_f_sptr self, int ninputs, int noutputs) -> bool"""
        return _fsk4.fsk4_generic_f_sptr_check_topology(self, ninputs, noutputs)


    def alias(self):
        """alias(fsk4_generic_f_sptr self) -> std::string"""
        return _fsk4.fsk4_generic_f_sptr_alias(self)


    def set_block_alias(self, name):
        """set_block_alias(fsk4_generic_f_sptr self, std::string name)"""
        return _fsk4.fsk4_generic_f_sptr_set_block_alias(self, name)


    def _post(self, which_port, msg):
        """_post(fsk4_generic_f_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _fsk4.fsk4_generic_f_sptr__post(self, which_port, msg)


    def message_ports_in(self):
        """message_ports_in(fsk4_generic_f_sptr self) -> swig_int_ptr"""
        return _fsk4.fsk4_generic_f_sptr_message_ports_in(self)


    def message_ports_out(self):
        """message_ports_out(fsk4_generic_f_sptr self) -> swig_int_ptr"""
        return _fsk4.fsk4_generic_f_sptr_message_ports_out(self)


    def message_subscribers(self, which_port):
        """message_subscribers(fsk4_generic_f_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _fsk4.fsk4_generic_f_sptr_message_subscribers(self, which_port)

fsk4_generic_f_sptr_swigregister = _fsk4.fsk4_generic_f_sptr_swigregister
fsk4_generic_f_sptr_swigregister(fsk4_generic_f_sptr)


fsk4_generic_f_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id ())


def generic_f(queue, processing_flags):
    """generic_f(msg_queue_sptr queue, int processing_flags) -> fsk4_generic_f_sptr"""
    return _fsk4.generic_f(queue, processing_flags)
class fsk4_apco25_f_sptr(object):
    """Proxy of C++ boost::shared_ptr<(fsk4_apco25_f)> class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        __init__(boost::shared_ptr<(fsk4_apco25_f)> self) -> fsk4_apco25_f_sptr
        __init__(boost::shared_ptr<(fsk4_apco25_f)> self, fsk4_apco25_f * p) -> fsk4_apco25_f_sptr
        """
        this = _fsk4.new_fsk4_apco25_f_sptr(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def __deref__(self):
        """__deref__(fsk4_apco25_f_sptr self) -> fsk4_apco25_f *"""
        return _fsk4.fsk4_apco25_f_sptr___deref__(self)

    __swig_destroy__ = _fsk4.delete_fsk4_apco25_f_sptr
    __del__ = lambda self: None

    def history(self):
        """history(fsk4_apco25_f_sptr self) -> unsigned int"""
        return _fsk4.fsk4_apco25_f_sptr_history(self)


    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(fsk4_apco25_f_sptr self, int which, int delay)
        declare_sample_delay(fsk4_apco25_f_sptr self, unsigned int delay)
        """
        return _fsk4.fsk4_apco25_f_sptr_declare_sample_delay(self, *args)


    def sample_delay(self, which):
        """sample_delay(fsk4_apco25_f_sptr self, int which) -> unsigned int"""
        return _fsk4.fsk4_apco25_f_sptr_sample_delay(self, which)


    def output_multiple(self):
        """output_multiple(fsk4_apco25_f_sptr self) -> int"""
        return _fsk4.fsk4_apco25_f_sptr_output_multiple(self)


    def relative_rate(self):
        """relative_rate(fsk4_apco25_f_sptr self) -> double"""
        return _fsk4.fsk4_apco25_f_sptr_relative_rate(self)


    def start(self):
        """start(fsk4_apco25_f_sptr self) -> bool"""
        return _fsk4.fsk4_apco25_f_sptr_start(self)


    def stop(self):
        """stop(fsk4_apco25_f_sptr self) -> bool"""
        return _fsk4.fsk4_apco25_f_sptr_stop(self)


    def nitems_read(self, which_input):
        """nitems_read(fsk4_apco25_f_sptr self, unsigned int which_input) -> uint64_t"""
        return _fsk4.fsk4_apco25_f_sptr_nitems_read(self, which_input)


    def nitems_written(self, which_output):
        """nitems_written(fsk4_apco25_f_sptr self, unsigned int which_output) -> uint64_t"""
        return _fsk4.fsk4_apco25_f_sptr_nitems_written(self, which_output)


    def max_noutput_items(self):
        """max_noutput_items(fsk4_apco25_f_sptr self) -> int"""
        return _fsk4.fsk4_apco25_f_sptr_max_noutput_items(self)


    def set_max_noutput_items(self, m):
        """set_max_noutput_items(fsk4_apco25_f_sptr self, int m)"""
        return _fsk4.fsk4_apco25_f_sptr_set_max_noutput_items(self, m)


    def unset_max_noutput_items(self):
        """unset_max_noutput_items(fsk4_apco25_f_sptr self)"""
        return _fsk4.fsk4_apco25_f_sptr_unset_max_noutput_items(self)


    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(fsk4_apco25_f_sptr self) -> bool"""
        return _fsk4.fsk4_apco25_f_sptr_is_set_max_noutput_items(self)


    def set_min_noutput_items(self, m):
        """set_min_noutput_items(fsk4_apco25_f_sptr self, int m)"""
        return _fsk4.fsk4_apco25_f_sptr_set_min_noutput_items(self, m)


    def min_noutput_items(self):
        """min_noutput_items(fsk4_apco25_f_sptr self) -> int"""
        return _fsk4.fsk4_apco25_f_sptr_min_noutput_items(self)


    def max_output_buffer(self, i):
        """max_output_buffer(fsk4_apco25_f_sptr self, int i) -> long"""
        return _fsk4.fsk4_apco25_f_sptr_max_output_buffer(self, i)


    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(fsk4_apco25_f_sptr self, long max_output_buffer)
        set_max_output_buffer(fsk4_apco25_f_sptr self, int port, long max_output_buffer)
        """
        return _fsk4.fsk4_apco25_f_sptr_set_max_output_buffer(self, *args)


    def min_output_buffer(self, i):
        """min_output_buffer(fsk4_apco25_f_sptr self, int i) -> long"""
        return _fsk4.fsk4_apco25_f_sptr_min_output_buffer(self, i)


    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(fsk4_apco25_f_sptr self, long min_output_buffer)
        set_min_output_buffer(fsk4_apco25_f_sptr self, int port, long min_output_buffer)
        """
        return _fsk4.fsk4_apco25_f_sptr_set_min_output_buffer(self, *args)


    def pc_noutput_items(self):
        """pc_noutput_items(fsk4_apco25_f_sptr self) -> float"""
        return _fsk4.fsk4_apco25_f_sptr_pc_noutput_items(self)


    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(fsk4_apco25_f_sptr self) -> float"""
        return _fsk4.fsk4_apco25_f_sptr_pc_noutput_items_avg(self)


    def pc_noutput_items_var(self):
        """pc_noutput_items_var(fsk4_apco25_f_sptr self) -> float"""
        return _fsk4.fsk4_apco25_f_sptr_pc_noutput_items_var(self)


    def pc_nproduced(self):
        """pc_nproduced(fsk4_apco25_f_sptr self) -> float"""
        return _fsk4.fsk4_apco25_f_sptr_pc_nproduced(self)


    def pc_nproduced_avg(self):
        """pc_nproduced_avg(fsk4_apco25_f_sptr self) -> float"""
        return _fsk4.fsk4_apco25_f_sptr_pc_nproduced_avg(self)


    def pc_nproduced_var(self):
        """pc_nproduced_var(fsk4_apco25_f_sptr self) -> float"""
        return _fsk4.fsk4_apco25_f_sptr_pc_nproduced_var(self)


    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(fsk4_apco25_f_sptr self, int which) -> float
        pc_input_buffers_full(fsk4_apco25_f_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_apco25_f_sptr_pc_input_buffers_full(self, *args)


    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(fsk4_apco25_f_sptr self, int which) -> float
        pc_input_buffers_full_avg(fsk4_apco25_f_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_apco25_f_sptr_pc_input_buffers_full_avg(self, *args)


    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(fsk4_apco25_f_sptr self, int which) -> float
        pc_input_buffers_full_var(fsk4_apco25_f_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_apco25_f_sptr_pc_input_buffers_full_var(self, *args)


    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(fsk4_apco25_f_sptr self, int which) -> float
        pc_output_buffers_full(fsk4_apco25_f_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_apco25_f_sptr_pc_output_buffers_full(self, *args)


    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(fsk4_apco25_f_sptr self, int which) -> float
        pc_output_buffers_full_avg(fsk4_apco25_f_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_apco25_f_sptr_pc_output_buffers_full_avg(self, *args)


    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(fsk4_apco25_f_sptr self, int which) -> float
        pc_output_buffers_full_var(fsk4_apco25_f_sptr self) -> pmt_vector_float
        """
        return _fsk4.fsk4_apco25_f_sptr_pc_output_buffers_full_var(self, *args)


    def pc_work_time(self):
        """pc_work_time(fsk4_apco25_f_sptr self) -> float"""
        return _fsk4.fsk4_apco25_f_sptr_pc_work_time(self)


    def pc_work_time_avg(self):
        """pc_work_time_avg(fsk4_apco25_f_sptr self) -> float"""
        return _fsk4.fsk4_apco25_f_sptr_pc_work_time_avg(self)


    def pc_work_time_var(self):
        """pc_work_time_var(fsk4_apco25_f_sptr self) -> float"""
        return _fsk4.fsk4_apco25_f_sptr_pc_work_time_var(self)


    def pc_work_time_total(self):
        """pc_work_time_total(fsk4_apco25_f_sptr self) -> float"""
        return _fsk4.fsk4_apco25_f_sptr_pc_work_time_total(self)


    def pc_throughput_avg(self):
        """pc_throughput_avg(fsk4_apco25_f_sptr self) -> float"""
        return _fsk4.fsk4_apco25_f_sptr_pc_throughput_avg(self)


    def set_processor_affinity(self, mask):
        """set_processor_affinity(fsk4_apco25_f_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _fsk4.fsk4_apco25_f_sptr_set_processor_affinity(self, mask)


    def unset_processor_affinity(self):
        """unset_processor_affinity(fsk4_apco25_f_sptr self)"""
        return _fsk4.fsk4_apco25_f_sptr_unset_processor_affinity(self)


    def processor_affinity(self):
        """processor_affinity(fsk4_apco25_f_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _fsk4.fsk4_apco25_f_sptr_processor_affinity(self)


    def active_thread_priority(self):
        """active_thread_priority(fsk4_apco25_f_sptr self) -> int"""
        return _fsk4.fsk4_apco25_f_sptr_active_thread_priority(self)


    def thread_priority(self):
        """thread_priority(fsk4_apco25_f_sptr self) -> int"""
        return _fsk4.fsk4_apco25_f_sptr_thread_priority(self)


    def set_thread_priority(self, priority):
        """set_thread_priority(fsk4_apco25_f_sptr self, int priority) -> int"""
        return _fsk4.fsk4_apco25_f_sptr_set_thread_priority(self, priority)


    def name(self):
        """name(fsk4_apco25_f_sptr self) -> std::string"""
        return _fsk4.fsk4_apco25_f_sptr_name(self)


    def symbol_name(self):
        """symbol_name(fsk4_apco25_f_sptr self) -> std::string"""
        return _fsk4.fsk4_apco25_f_sptr_symbol_name(self)


    def input_signature(self):
        """input_signature(fsk4_apco25_f_sptr self) -> io_signature_sptr"""
        return _fsk4.fsk4_apco25_f_sptr_input_signature(self)


    def output_signature(self):
        """output_signature(fsk4_apco25_f_sptr self) -> io_signature_sptr"""
        return _fsk4.fsk4_apco25_f_sptr_output_signature(self)


    def unique_id(self):
        """unique_id(fsk4_apco25_f_sptr self) -> long"""
        return _fsk4.fsk4_apco25_f_sptr_unique_id(self)


    def to_basic_block(self):
        """to_basic_block(fsk4_apco25_f_sptr self) -> basic_block_sptr"""
        return _fsk4.fsk4_apco25_f_sptr_to_basic_block(self)


    def check_topology(self, ninputs, noutputs):
        """check_topology(fsk4_apco25_f_sptr self, int ninputs, int noutputs) -> bool"""
        return _fsk4.fsk4_apco25_f_sptr_check_topology(self, ninputs, noutputs)


    def alias(self):
        """alias(fsk4_apco25_f_sptr self) -> std::string"""
        return _fsk4.fsk4_apco25_f_sptr_alias(self)


    def set_block_alias(self, name):
        """set_block_alias(fsk4_apco25_f_sptr self, std::string name)"""
        return _fsk4.fsk4_apco25_f_sptr_set_block_alias(self, name)


    def _post(self, which_port, msg):
        """_post(fsk4_apco25_f_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _fsk4.fsk4_apco25_f_sptr__post(self, which_port, msg)


    def message_ports_in(self):
        """message_ports_in(fsk4_apco25_f_sptr self) -> swig_int_ptr"""
        return _fsk4.fsk4_apco25_f_sptr_message_ports_in(self)


    def message_ports_out(self):
        """message_ports_out(fsk4_apco25_f_sptr self) -> swig_int_ptr"""
        return _fsk4.fsk4_apco25_f_sptr_message_ports_out(self)


    def message_subscribers(self, which_port):
        """message_subscribers(fsk4_apco25_f_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _fsk4.fsk4_apco25_f_sptr_message_subscribers(self, which_port)

fsk4_apco25_f_sptr_swigregister = _fsk4.fsk4_apco25_f_sptr_swigregister
fsk4_apco25_f_sptr_swigregister(fsk4_apco25_f_sptr)


fsk4_apco25_f_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id ())


def apco25_f(queue, processing_flags):
    """apco25_f(msg_queue_sptr queue, int processing_flags) -> fsk4_apco25_f_sptr"""
    return _fsk4.apco25_f(queue, processing_flags)


